FROM node:latest

WORKDIR /app/frontend

COPY package*.json /.

RUN npm install

RUN npm install -g serve

COPY . .

ARG _PORT

ENV PORT ${_PORT}

RUN echo ${PORT}

RUN npm run build

EXPOSE ${PORT}

CMD serve -s build -l $PORT