version: '3.8'
services:
  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017   
    networks:
      - spliright-network 
    volumes:
      - /data/db  

  backend:
    build:
      context: backend
      dockerfile: dockerfile
    ports: 
      - 3000:3000
    environment:
      - JWT_SECRET=SECRET
      - MONGO_URI_DOCKER=mongodb://mongodb:27017
    networks:
      - spliright-network 
    depends_on:
      - mongodb
    healthcheck:
      test: curl --fail http://mongodb:27017 || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s    

  frontend1:   
    build:      
      context: frontend
      args:
        - _PORT=3001
      dockerfile: dockerfile
    ports:
      - 3001:3001
    environment:
      - REACT_APP_BACKEND_URL=http://backend:3000
    networks:
      - spliright-network 
    depends_on:
      - backend
    healthcheck:
      test: curl --fail http://backend:3000/health
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s   

  frontend2:   
    build:      
      context: frontend
      args:
        - _PORT=3002
      dockerfile: dockerfile
    ports:
      - 3002:3002
    environment:
      - REACT_APP_BACKEND_URL=http://backend:3000
    networks:
      - spliright-network 
    depends_on:
      - backend
    healthcheck:
      test: curl --fail http://backend:3000/health
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s 

  frontend3:   
    build:      
      context: frontend
      args:
        - _PORT=3003
      dockerfile: dockerfile
    ports:
      - 3003:3003
    environment:
      - REACT_APP_BACKEND_URL=http://backend:3000
    networks:
      - spliright-network 
    depends_on:
      - backend
    healthcheck:
      test: curl --fail http://backend:3000/health
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s 

networks:
  spliright-network:
      
    
