FROM node:latest

WORKDIR /app/backend

COPY package*.json /.

RUN npm install --force

COPY . .

ENV JWT_SECRET=SECRET MONGO_URI_DOCKER=mongodb://mongodb:27017

RUN npm run build

EXPOSE 3000

CMD [ "node", "/app/backend/dist/src/main.js" ]