###

POST http://localhost:3000/auth/login HTTP/1.1
content-type: application/json

{
    "username": "Max Mustermann",
    "password": "coolesPasswort"
}

###

GET http://localhost:3000/auth/account HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1heCBNdXN0ZXJtYW5uIiwic3ViIjoiY29vbGVzUGFzc3dvcnQiLCJpYXQiOjE2ODQyMzA1MzcsImV4cCI6MTY4NDMxNjkzN30.wJ25PxCGll41MfkQ69NuBcER0c6hr03LVyzAs4zqEY0


